### ISSUE TITLE
Default wallet null. Subscriptions don't work.

### ISSUE THREAD

**Issue by gamesgil** [heavy-duty/wallet-adapter#19]
OS: Windows 11
Browsers+wallets: Firefox+Phantom, Chrome+Solflare
Angular: ^17.3
wallet-adapter: ^0.8.4

Several issues:
1. Solflare doesn't seem to be supported
2. _this.wallets()[0].adapter?.name_ shows the default wallet (Phantom), but _this.wallet()_ is null
3. _this.wallets()[0].adapter.connect()_ works, but this._walletStore.wallet$.subscribe doesn't
4. Trying to connect with _this._walletStore.connect()_ returns an error: WalletNotSelectedError

Please help.

**Comment by danmt** [comment]
I recommend you to take a look at [this tutorial](https://github.com/heavy-duty/wallet-adapter/blob/main/examples/raw/README.md). 

1. Solflare should be supported since it supports any wallet that implements the Wallet Standard (Solflare is one of them).
2. The wallets list is determined by the wallets you have available, if you have Phantom installed, it will show.
3. Accessing the underlying adapter's `connect` method might work, but it won't update the state of the store, that's why `wallet$` should not change.
4. Before using the `connect` method from the wallet store it verifies that you have a wallet selected first. You have to use `selectWallet` method from the wallet store.

By the way, this project is not being actively maintained. While we try to keep it updated, it's been a while, so make sure to use the same Angular version as the package according to the version matrix in the README. 

If you are interested in supporting as a collaborator, feel free to reach out.

**Comment by gamesgil** [comment]
Thank you for your help. I've checked and:
readonly wallets = injectWallets();
this.wallets().length

This returns 0 with the Chrome+Solflare combo.
Interestingly enough, after a certain timeout, it starts recognizing the wallet and the code runs as expected.
Trouble is that a timeout isn't a reliable mechanism. Any idea how to hook onto the right moment?

**Comment by danmt** [comment]
The value of `wallets` is loaded synchronously when providing the services, which in your case might be an empty list or a hard-coded list of wallet adapters. Then, an asynchronous process checks all the installed wallets in your browser and adds them to `wallets`. BTW, `wallets` should update automatically once the adapters are loaded.
